### ISSUE TITLE
docker edgex mongo image

### ISSUE THREAD

**Issue by JPWKU** [edgexfoundry/ci-management#280]
This image has recently been updated; the merge job and release job do not work as they rely on reverse triggers to a maven job only.

**Comment by lranjbar** [comment]
Fixed in #282

**Comment by xmlviking** [comment]
Is this directly addressing the issue of the non arm docker image build for edgex-mongo?  I'm not seeing any new builds of the docker-edgex-mongo in nexus.  The original reason for this issue was around the edgex black box tests.  Some changes were made to the init_mongo.js file and a PR was completed.  Subsequently no new version of the docker-edgex-mongo image was created in either the merge or nightly.   If this was completed is there a way to version this image so we can tell that it has been updated?  We added new indexes and permissions to the mongo database but I don't seem to be able to see any tag or image artifact which tells me that.   Thanks!  :)

**Comment by JPWKU** [comment]
Fixed.  The docker-edgex-mongo images are now available in nexus staging.
