### ISSUE TITLE
Allow subset of developers to trigger a Jenkins job manually

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#295]
- requires a defined role in Jenkins to allow certain groups to trigger a job manually
 - similar to other LF Jenkins projects

US3471

**Comment by jamesrgregg** [comment]
[#68803] : Allow subset of developers to trigger a Jenkins job manually
submitted ticket to EdgeX helpdesk

**Comment by eb-oss** [comment]
@jamesrgregg @JPWKU Who would you like included in this group? Please provide email addresses (I've already sent an invite to @JPWKU). Feel free to put them on the RT ticket rather than here, in order to reduce their visibility.

@JPWKU Once you've accepted the invite, please login to Jenkins and let me know if the permissions are setup correctly.

**Comment by jamesrgregg** [comment]
Please add @tonyespy and @anonymouse64  for now.

**Comment by eb-oss** [comment]
The group has been created, and all invites have been sent and accepted. Could someone in the group (@JPWKU @tonyespy @anonymouse64) confirm that they now have the option to manually trigger jobs in the Jenkins UI?

**Comment by eb-oss** [comment]
@JPWKU @tonyespy @anonymouse64 Please test this so that the ticket can be closed or fixed.

**Comment by anonymouse64** [comment]
@MightyNerdEric I just checked and I was able to trigger a build manually with parameters, see https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-release-snap/1/

**Comment by eb-oss** [comment]
Excellent, thanks for following up. Closing this issue.
