### ISSUE TITLE
New build automation for docker-edgex-mongo bootstrap

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/ci-management#460]
New build automation for docker-edgex-mongo bootstrap
[US5088] (https://rally1.rallydev.com/#/detail/userstory/327878882852?fdp=true)

**Comment by tsconn23** [comment]
Update on this -- We're close to being able to merge the following PR which contains the new Go application. Note that the `default` verify job is failing due to the Dockerfiles being moved into the cmd directory. That will need to be adjusted.

https://github.com/edgexfoundry/docker-edgex-mongo/pull/35

**Comment by lranjbar** [comment]
Fixed with #477
